#mvn spring-boot:run
project:
  artifactId: spring-io
  name: spring-io
  description: spring-io

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
server:
  port: 8080
  servlet:
    context-path: /demo
spring:
 # h2:
   # console:
     # settings:
        #web-allow-other:  true
      #path: /h2-console
      #enabled: true
 # datasource:
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:test
    #username: sa
    #password:
  #jpa:
    #database: h2
    #hibernate:
      #ddl-auto: create-drop
      #show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC