#mvn spring-boot:run
project:
  artifactId: spring-io
  name: spring-io
  description: spring-io

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}

spring:
#  h2:
#    console:
#      settings:
#        web-allow-other:  true
#      path: /h2-console
#      enabled: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test1?&useSSL=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC