project:
  artifactId: spring-io
  name: spring-io
  description: spring-io
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/boot?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC